"""Initial database build

Revision ID: 90af1d83a924
Revises: 
Create Date: 2025-11-04 19:27:31.632529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90af1d83a924'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ngo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ngo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ngo_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('total_waste_diverted_kg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_type', sa.String(length=50), nullable=False),
    sa.Column('estimated_weight_kg', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('image_filename', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ngo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donation_donation_type'), ['donation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_donation_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donation_timestamp'))
        batch_op.drop_index(batch_op.f('ix_donation_donation_type'))

    op.drop_table('donation')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('ngo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ngo_name'))

    op.drop_table('ngo')
    # ### end Alembic commands ###
